###
POST http://127.0.0.1:8000/api/auth/register/
Content-Type: application/json

{
  "email": "ogennaisrael@gmail.com",
  "username": "Ogenna01",
  "password": "0987poiu",
  "password_confirm": "0987poiu"
}

###
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
  "email": "ogennaisrael@gmail.com",
  "password": "0987poiu"
}


### GET request to example server
GET http://127.0.0.1:8000/api/auth/profile/me/
Content-Type: application/json
Authorization: Bearer eyJ

###
GET http://127.0.0.1:8000/api/wallet/
Content-Type: application/json
Authorization: Bearer ey
###

POST http://127.0.0.1:8000/api/deposit/
Content-Type: application/json
Authorization: Bearer e

{
  "amount": 300,
  "idempotency_key": "idempotency_key___038"
}

###
POST http://127.0.0.1:8000/api/verify_deposit/
Content-Type: application/json
Authorization: Bearer e

{
  "payment_reference": "fE3dFcDa670924eA"
}

###
POST http://127.0.0.1:8000/api/set_transaction_pin/
Content-Type: application/json
Authorization: Bearer e
{
  "pin": "0303",
  "confirm_pin": "0303"
}

###
POST http://127.0.0.1:8000/api/transfer/
Content-Type: application/json
Authorization: Bearer ...

{
  "amount": 200,
  "account_number": "5819109103",
  "transaction_pin": "0303",
  "idempotency_key": "idempotency_0003eek33"

}

###
POST http://127.0.0.1:8000/api/verify_transfer/
Content-Type: application/json
Authorization: Bearer ey..

{
  "payment_reference": "E823517bCeAfadF4"
}

###
POST http://127.0.0.1:8000/api/withdraw/
Content-Type: application/json
Authorization: Bearer ey..

{
  "account_number": "0948479383",
  "bank_name": "opay",
  "bank_code": "09484",
  "account_name": "user002",
  "idempotency_key": "idempotency_key",
  "amount": "150",
  "transaction_pin": "0303"

}