# Generated by Django 6.0.3 on 2026-03-17 21:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountNumber',
            fields=[
                ('number_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('hashed', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Account Number',
                'verbose_name_plural': 'account numbers',
                'indexes': [models.Index(fields=['account_number'], name='wallet_acco_account_f21c03_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('wallet_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('currency', models.CharField(blank=True, default='NGN', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet', to='wallet.accountnumber')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Wallet',
                'verbose_name_plural': 'User wallets',
                'indexes': [models.Index(fields=['balance'], name='wallet_user_balance_890455_idx'), models.Index(fields=['currency'], name='wallet_user_currenc_543cba_idx'), models.Index(fields=['created_at'], name='wallet_user_created_3912e4_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'account_number'), name='owner_unique')],
            },
        ),
    ]
