# Generated by Django 6.0.3 on 2026-03-18 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallettransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddIndex(
            model_name='userwallet',
            index=models.Index(fields=['previous_balance'], name='wallet_user_previou_a9caeb_idx'),
        ),
    ]
