# Generated by Django 6.0.3 on 2026-03-18 12:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_userwallet_previous_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferPin',
            fields=[
                ('pin_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('pin', models.CharField(max_length=10)),
                ('hashed_pin', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_pin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Pin',
                'verbose_name_plural': 'Transaction pins',
                'indexes': [models.Index(fields=['pin'], name='wallet_tran_pin_d395d4_idx'), models.Index(fields=['hashed_pin'], name='wallet_tran_hashed__20e26f_idx')],
            },
        ),
    ]
