# Generated by Django 6.0.3 on 2026-03-18 15:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_transferpin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountnumber',
            name='hashed',
            field=models.BinaryField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='transferpin',
            name='hashed_pin',
            field=models.BinaryField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('transfer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Pending', 'Pending'), ('Failed', 'Failed'), ('Success', 'Success')], default='Pending', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver_wallet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_wallet', to='wallet.userwallet')),
                ('sender_wallet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_wallet', to='wallet.userwallet')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'indexes': [models.Index(fields=['status'], name='wallet_tran_status_a63693_idx'), models.Index(fields=['amount'], name='wallet_tran_amount_c68d2f_idx'), models.Index(fields=['reference'], name='wallet_tran_referen_517055_idx'), models.Index(fields=['created_at'], name='wallet_tran_created_e0c119_idx')],
            },
        ),
    ]
