# Generated by Django 6.0.3 on 2026-03-18 20:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_accountnumber_hashed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('withdraw_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Pending', 'Pending'), ('Failed', 'Failed'), ('Success', 'Success')], default='Pending', max_length=50)),
                ('account_name', models.CharField(max_length=255, null=True)),
                ('bank_code', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraws', to='wallet.userwallet')),
            ],
            options={
                'verbose_name': 'Withdraw',
                'verbose_name_plural': 'withdrawals',
                'indexes': [models.Index(fields=['reference'], name='wallet_with_referen_e10453_idx'), models.Index(fields=['amount'], name='wallet_with_amount_7f82b2_idx'), models.Index(fields=['status'], name='wallet_with_status_4e6cca_idx'), models.Index(fields=['created_at'], name='wallet_with_created_a4ec4c_idx')],
            },
        ),
    ]
